### ISSUE TITLE
Error Unexpected token <

### ISSUE THREAD

**Issue by dpyudha** [jsantana90/nextjs-redux-boilerplate#2]
i had been create some page, but sometimes, i got this error when i click a navbar

Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0

what should i do ?
thankyou

**Comment by johhansantana** [comment]
Hey @dpyudha I've just cloned the repo and got no errors navigating around the two pages.

Check that you installed npm packages by doing `npm install` it's all I can think off right now without actually seeing your code.
